// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// ...
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr5OsyI7J4kU-iTn6YLgoLo2NHRLPVsrE',
    appId: '1:261373123393:web:c8e8d2bbad62f0dfef5fc0',
    messagingSenderId: '261373123393',
    projectId: 'ceoldevs',
    authDomain: 'ceoldevs.firebaseapp.com',
    storageBucket: 'ceoldevs.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLltAE4dOefgYk5c5z3mRBW4fY_EfvcY8',
    appId: '1:261373123393:android:41d32123461b1f95ef5fc0',
    messagingSenderId: '261373123393',
    projectId: 'ceoldevs',
    storageBucket: 'ceoldevs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa9BgylboPf9HDhXWVkTiiOQJJ0ThcBMI',
    appId: '1:261373123393:ios:14925fe504037100ef5fc0',
    messagingSenderId: '261373123393',
    projectId: 'ceoldevs',
    storageBucket: 'ceoldevs.appspot.com',
    iosClientId:
        '261373123393-1crmspngg8nuu5bjkhf2f2lmdg4q18bi.apps.googleusercontent.com',
    iosBundleId: 'com.example.xpensio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa9BgylboPf9HDhXWVkTiiOQJJ0ThcBMI',
    appId: '1:261373123393:ios:14925fe504037100ef5fc0',
    messagingSenderId: '261373123393',
    projectId: 'ceoldevs',
    storageBucket: 'ceoldevs.appspot.com',
    iosClientId:
        '261373123393-1crmspngg8nuu5bjkhf2f2lmdg4q18bi.apps.googleusercontent.com',
    iosBundleId: 'com.example.xpensio',
  );
}
